language: php

php:
  - '7.1'
  - '7.2'

sudo: false

notifications:
  email: false

env:
  global:
    # AWS creds
    - secure: "Q5s7QEoKdluVhpwUnOM1u/cpJqclA+IoA7f8IXFm/4fBEeOYF4ANvJuKC683vHcRgBZlpsEy3DxnLL60GRP5VjSxRY8yorQqft2AXcb+lEtGaJRSnOS2YKgNvSYn5pNM/F9kDDTD8GcRa7Sn2SRHa7/XIdZYn7XiSOjavrNbd5x9t0SVAbfC7D5/rl5cI4xWQH2he/M1gifL4as4WX25dsGExgggyGh8n9WH1CvIdE9EHgiOFWsOhlkN2C6agwiuWHLOZOo74F5Bud2kD0/Z7kojJz0BvBGULxX70EPT4pihEVP2PybHX9WoraAiLYnByxpNVAmnHSt6AIORjOLBEVhzkP9pIrgo6BUmQ3zQHBxrLnFkVBSJ2zaBGaVW4movDfEShd2cTLA/oM42rJQRDcIwtKN4Gpwf//Ji4+x/bnWYBefRQBj9J6dePjUreOtvDCfQ6sI4YbQ6qD+E6HL8t0fkEpH3z0juaH/2AfGEnJPX4K5Fd8BNzsMc20M/fHhBFIqn1PEnOspgJJeHWgNO80W47z2IRnQmxT5wYYG/NjM1+IrrFCkJG2UrwqNEBkbOIKlUAD+BShNCE08iu6l10pOFW9K7X10MkWnywXa2lBhL6nkmjdBQILBaD2qtvhsZMgcagcdmwA/tL89UppoRCyJ8ZRlLBBKJenj2QyNihz8="
    - secure: "LCywaIpo6dlIMMSXyyRZdgpnS0EN5rNpYNl0WaWffBYooVNufnL+av1RIH7BEu00jK4F0KWS/ltozuApypX0btR0KXaIZ87QImc9LXxgckqq33gwQ9aAT50eqiuOiaH9W2dyBifXM6x++zHQJ966zGmM3xfom+wmwEiQ7/iZtD9PjDRoYiYIkaF73NNIRfE5mXyNdFd5Yc19k1NN19rtWxocGyq78odvDcdkqpxm/wUyMv1lEDgqsaVqKJHPaZHrkqIsCd4IbrO+HEu6cY5XIHvsbXOYjUIeAKwnca4ZwSqu/B9XdUL1RZ5ag9LuwdzxUQm220LxFwftZVrnFCwHI2ooMF8C0wQcojTvnsskHMRLJNXE+LFlFWY2ddPer6rlgtBgII2hkQ9gVm6jgfVlEm/2/y+6W1mFfj77gGXASgrsq47HXNUDZR9Q4rS7gFPyUXnQRBja691SEyAf3Df+RyKVFptMLyQeACqcnrrJwJBS+H5ggOdRL3gLC+PUXu1JTlMqgGXjVXfn6y1iMRt2xoWc/gcRN/pIOXWUKBak6JhJ7OUf7ooSDskSazdCKA5kPX6J0icMJXFfTzskOfOLkzwNy8X02UQ8HlwyQWud/n6VvwVnSnmesTRg0fJf6wR4EyhLCDNrFLxVjxVapKlmQcWALvPx1Pn+Fk5/6jS8QOo="
    - CREDCOMMANDS_KEY_ID=alias/pmg-cred-commands-tester

install:
  - composer install

script:
  - ./vendor/bin/phpunit -v
