language: php

php:
  - '7.4'
  - '8.0'

sudo: false

notifications:
  email: false

services:
  - docker

env:
  global:
    - DOCKER_USERNAME=agencypmg
    # DOCKER_PASSWORD
    - secure: "qLU/Bb6aPMFB8q8CD/gxZDi1fWl6jifM/sodr+QW4FFWs7ZF/sJYBjobZ+nHBfaHvyYZrDtiZP3b3tai4z7yl9+7BA6I8Br3E6Feu8ZLV+oRbmQ4ARvApcTXKCMABA0ICody/znaJZErq5anG53lj6JWE/uzXz9h68OQ7BWXFRD1U7x2GcRY0vxy90AwgmZ3XD5aChfoliEdQG6ry+euypzChx2rprc9QqndUDh0shPxhlSfLk5h6FPM294EBC5MZzrVRhxWrz3flxp2mgCFVhMMqmf5Eivxj5qRC0vyjdRSwN2+3P8Mfa4nRQ1Yr3SKPM+yLcWYm8/3zFBfnhQ7iKd+Hik7env99Ta86JWItt4Ah27ZTCWiCB07MNcOluN/yeJraByPJbadD2f8sHzsuKh6DFnuzABFBGFGe3iOAsAVIMIFllww7on8gOKzMJA5OvokWhv9FtqF2nuVQzNA5rtnA6b+l9ffnbbVcf1/yh54wxHtqMc781JgqiukqgoBohIrkfazSew3T2RO2jn4E5UkWiP4PNh5nAg3bSaf2hH9nhImqi8ZPtKOuoDAuLssRewW8V6Ngqwfd3EDbIKaoRw5YBhyrJQ6ejQTwwLdiaHgiT4o6zbgJpWa9EzLQXFaoQDbdjdcZ1n4qKLlCKfQz1IXz+8uDkJQi1MKZX04H6E="


before_install:
  - ./bin/dev/docker-compose up -d

install:
  - composer install

script:
  - ./bin/dev/unittest -v
